In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2022-ipl-auction-dataset/ipl-2022-auction-dataset.ipynb

# Initialising the URL

In [2]:
url="https://www.news18.com/cricketnext/ipl-auction-2022/mi-players-list-8/"

# Reading the URL using real_html()

In [3]:
initial=pd.read_html(url)

In [4]:
initial

[    #           Player | Squad Base Price          TYPE  COST IN ₹ (CR.)  \
 0   1        Ishan Kishan | MI       2 Cr  WICKETKEEPER            15.25
 1   2      Deepak Chahar | CSK       2 Cr        BOWLER            14.00
 2   3       Shreyas Iyer | KKR       2 Cr        BATTER            12.25
 3   4  Liam Livingstone | PBKS       1 Cr   ALL-ROUNDER            11.50
 4   5      Harshal Patel | RCB       2 Cr   ALL-ROUNDER            10.75
 5   6  Wanindu Hasaranga | RCB       1 Cr   ALL-ROUNDER            10.75
 6   7    Nicholas Pooran | SRH     1.5 Cr  WICKETKEEPER            10.75
 7   8      Shardul Thakur | DC       2 Cr        BOWLER            10.75
 8   9     Prasidh Krishna | RR       1 Cr        BOWLER            10.00
 9  10         Avesh Khan | LSG    20 Lakh        BOWLER            10.00

    Cost IN $ (000) 2021 Squad
 0           1982.5         MI
 1           1820.0        CSK
 2           1592.5         DC
 3           1495.0         RR
 4           1397.5        RCB
 5           1397.5        RCB
 6           1397.5       PBKS
 7           1397.5        CSK
 8           1300.0        KKR
 9           1300.0         DC  ,
           2022 Squad GT  Base Price          TYPE  COST IN ₹ (CR.)  \
 0           Rashid Khan  Draft Pick        BOWLER            15.00
 1         Hardik Pandya  Draft Pick   ALL-ROUNDER            15.00
 2       Lockie Ferguson        2 Cr        BOWLER            10.00
 3         Rahul Tewatia     40 Lakh   ALL-ROUNDER             9.00
 4          Shubman Gill  Draft Pick        BATTER             8.00
 5        Mohammad Shami        2 Cr        BOWLER             6.25
 6            Yash Dayal     20 Lakh        BOWLER             3.20
 7          David Miller        1 Cr        BATTER             3.00
 8        R. Sai Kishore     20 Lakh        BOWLER             3.00
 9   Abhinav Sadarangani     20 Lakh        BATTER             2.60
 10         Matthew Wade        2 Cr  WICKETKEEPER             2.40
 11       Alzarri Joseph     75 Lakh        BOWLER             2.40
 12            Jason Roy        2 Cr        BATTER             2.00
 13      Wriddhiman Saha        1 Cr  WICKETKEEPER             1.90
 14         Jayant Yadav        1 Cr   ALL-ROUNDER             1.70
 15        Vijay Shankar     50 Lakh   ALL-ROUNDER             1.40
 16       Dominic Drakes     75 Lakh   ALL-ROUNDER             1.10
 17          Varun Aaron     50 Lakh        BOWLER             0.50
 18      Gurkeerat Singh     50 Lakh   ALL-ROUNDER             0.50
 19           Noor Ahmad     30 Lakh        BOWLER             0.30
 20     Darshan Nalkande     20 Lakh   ALL-ROUNDER             0.20
 21      Pradeep Sangwan     20 Lakh   ALL-ROUNDER             0.20

     Cost IN $ (000) 2021 Squad
 0            1950.0        SRH
 1            1950.0         MI
 2            1300.0        KKR
 3            1170.0         RR
 4            1040.0        KKR
 5             812.5       PBKS
 6             416.0        NaN
 7             390.0         RR
 8             390.0        CSK
 9             338.0        NaN
 10            312.0        NaN
 11            312.0        NaN
 12            260.0        SRH
 13            247.0        SRH
 14            221.0         MI
 15            182.0        SRH
 16            143.0        CSK
 17             65.0        NaN
 18             65.0        KKR
 19             39.0        NaN
 20             26.0       PBKS
 21             26.0        NaN  ,
             2022 Squad CSK Base Price          TYPE  COST IN ₹ (CR.)  \
 0          Ravindra Jadeja   Retained   ALL-ROUNDER            16.00
 1            Deepak Chahar       2 Cr        BOWLER            14.00
 2                 MS Dhoni   Retained  WICKETKEEPER            12.00
 3                Moeen Ali   Retained   ALL-ROUNDER             8.00
 4            Ambati Rayudu       2 Cr  WICKETKEEPER             6.75
 5          Ruturaj Gaikwad   Retained        BATTER             6.00
 6             Dwayne Bravo       2 Cr   ALL-ROUNDER             4.40
 7              Shivam Dube    50 Lakh   ALL-ROUNDER             4.00
 8             Chris Jordan       2 Cr   ALL-ROUNDER             3.60
 9            Robin Uthappa       2 Cr        BATTER             2.00
 10        Mitchell Santner       1 Cr   ALL-ROUNDER             1.90
 11              Adam Milne     1.5 Cr        BOWLER             1.90
 12  Rajvardhan Hangargekar    30 Lakh   ALL-ROUNDER             1.50
 13        Prashant Solanki    20 Lakh        BOWLER             1.20
 14            Devon Conway       1 Cr        BATTER             1.00
 15      Maheesh Theekshana    50 Lakh        BOWLER             0.70
 16        Dwaine Pretorius    50 Lakh   ALL-ROUNDER             0.50
 17         K.Bhagath Varma    20 Lakh   ALL-ROUNDER             0.20
 18         Simarjeet Singh    20 Lakh        BOWLER             0.20
 19           N. Jagadeesan    20 Lakh  WICKETKEEPER             0.20
 20        C.Hari Nishaanth    20 Lakh        BATTER             0.20
 21               K.M. Asif    20 Lakh        BOWLER             0.20
 22        Tushar Deshpande    20 Lakh        BOWLER             0.20
 23     Subhranshu Senapati    20 Lakh        BATTER             0.20
 24        Mukesh Choudhary    20 Lakh        BOWLER             0.20

     Cost IN $ (000) 2021 Squad
 0            2080.0        CSK
 1            1820.0        CSK
 2            1560.0        CSK
 3            1040.0        CSK
 4             877.5        CSK
 5             780.0        CSK
 6             572.0        CSK
 7             520.0         RR
 8             468.0       PBKS
 9             260.0        CSK
 10            247.0        CSK
 11            247.0         MI
 12            195.0        NaN
 13            156.0        NaN
 14            130.0        NaN
 15             91.0        NaN
 16             65.0        NaN
 17             26.0        CSK
 18             26.0         MI
 19             26.0        CSK
 20             26.0        CSK
 21             26.0        CSK
 22             26.0        NaN
 23             26.0        NaN
 24             26.0        NaN  ,
          2022 Squad DC Base Price          TYPE  COST IN ₹ (CR.)  \
 0         Rishabh Pant   Retained  WICKETKEEPER            16.00
 1       Shardul Thakur       2 Cr        BOWLER            10.75
 2           Axar Patel   Retained   ALL-ROUNDER             9.00
 3         Prithvi Shaw   Retained        BATTER             7.50
 4       Mitchell Marsh       2 Cr   ALL-ROUNDER             6.50
 5        Anrich Nortje   Retained        BOWLER             6.50
 6         David Warner       2 Cr        BATTER             6.25
 7   Syed Khaleel Ahmed    50 Lakh        BOWLER             5.25
 8      Chetan Sakariya    50 Lakh        BOWLER             4.20
 9        Rovman Powell    75 Lakh        BATTER             2.80
 10         K.S. Bharat    20 Lakh  WICKETKEEPER             2.00
 11   Mustafizur Rahman       2 Cr        BOWLER             2.00
 12       Kuldeep Yadav       1 Cr        BOWLER             2.00
 13   Kamlesh Nagarkoti    40 Lakh   ALL-ROUNDER             1.10
 14       Mandeep Singh    50 Lakh        BATTER             1.10
 15         Lalit Yadav    20 Lakh   ALL-ROUNDER             0.65
 16         Tim Seifert    50 Lakh  WICKETKEEPER             0.50
 17        Pravin Dubey    20 Lakh   ALL-ROUNDER             0.50
 18     Lungisani Ngidi    50 Lakh        BOWLER             0.50
 19          Yash Dhull    20 Lakh   ALL-ROUNDER             0.50
 20       Ashwin Hebbar    20 Lakh        BATTER             0.20
 21       Sarfaraz Khan    20 Lakh   ALL-ROUNDER             0.20
 22         Ripal Patel    20 Lakh   ALL-ROUNDER             0.20
 23        Vicky Ostwal    20 Lakh   ALL-ROUNDER             0.20

     Cost IN $ (000) 2021 Squad
 0            2080.0         DC
 1            1397.5        CSK
 2            1170.0         DC
 3             975.0         DC
 4             845.0        NaN
 5             845.0         DC
 6             812.5        SRH
 7             682.5        SRH
 8             546.0         RR
 9             364.0        NaN
 10            260.0        RCB
 11            260.0         RR
 12            260.0        KKR
 13            143.0        KKR
 14            143.0       PBKS
 15             84.5         DC
 16             65.0        KKR
 17             65.0         DC
 18             65.0        CSK
 19             65.0        NaN
 20             26.0        NaN
 21             26.0       PBKS
 22             26.0         DC
 23             26.0        NaN  ,
          2022 Squad KKR Base Price          TYPE  COST IN ₹ (CR.)  \
 0          Shreyas Iyer       2 Cr        BATTER            12.25
 1         Andre Russell   Retained   ALL-ROUNDER            12.00
 2           Nitish Rana       1 Cr   ALL-ROUNDER             8.00
 3        Venkatesh Iyer   Retained   ALL-ROUNDER             8.00
 4   Varun Chakaravarthy   Retained        BOWLER             8.00
 5           Pat Cummins       2 Cr   ALL-ROUNDER             7.25
 6           Shivam Mavi    40 Lakh   ALL-ROUNDER             7.25
 7          Sunil Narine   Retained   ALL-ROUNDER             6.00
 8          Sam Billings       2 Cr  WICKETKEEPER             2.00
 9           Umesh Yadav       2 Cr        BOWLER             2.00
 10          Tim Southee     1.5 Cr        BOWLER             1.50
 11           Alex Hales     1.5 Cr        BATTER             1.50
 12       Ajinkya Rahane       1 Cr        BATTER             1.00
 13        Mohammad Nabi       1 Cr   ALL-ROUNDER             1.00
 14      Sheldon Jackson    30 Lakh  WICKETKEEPER             0.60
 15          Rinku Singh    20 Lakh        BATTER             0.55
 16         Ashok Sharma    20 Lakh        BOWLER             0.55
 17  Chamika Karunaratne    50 Lakh   ALL-ROUNDER             0.50
 18       Abhijeet Tomar    20 Lakh        BATTER             0.40
 19           Rasikh Dar    20 Lakh        BOWLER             0.20
 20           Anukul Roy    20 Lakh   ALL-ROUNDER             0.20
 21       Baba Indrajith    20 Lakh  WICKETKEEPER             0.20
 22            Aman Khan    20 Lakh   ALL-ROUNDER             0.20
 23         Ramesh Kumar    20 Lakh        BATTER             0.20
 24        Pratham Singh    20 Lakh        BATTER             0.20

     Cost IN $ (000) 2021 Squad
 0            1592.5         DC
 1            1560.0        KKR
 2            1040.0        KKR
 3            1040.0        KKR
 4            1040.0        KKR
 5             942.5        KKR
 6             942.5        KKR
 7             780.0        KKR
 8             260.0         DC
 9             260.0         DC
 10            195.0        KKR
 11            195.0        NaN
 12            130.0         DC
 13            130.0        SRH
 14             78.0        KKR
 15             71.5        NaN
 16             71.5        NaN
 17             65.0        NaN
 18             52.0        NaN
 19             26.0        NaN
 20             26.0         MI
 21             26.0        NaN
 22             26.0        NaN
 23             26.0        NaN
 24             26.0        NaN  ,
         2022 Squad PBKS Base Price          TYPE  COST IN ₹ (CR.)  \
 0        Mayank Agarwal   Retained        BATTER            12.00
 1      Liam Livingstone       1 Cr   ALL-ROUNDER            11.50
 2         Kagiso Rabada       2 Cr        BOWLER             9.25
 3         Shahrukh Khan    40 Lakh   ALL-ROUNDER             9.00
 4        Shikhar Dhawan       2 Cr        BATTER             8.25
 5        Jonny Bairstow     1.5 Cr  WICKETKEEPER             6.75
 6           Odean Smith       1 Cr   ALL-ROUNDER             6.00
 7          Rahul Chahar    75 Lakh        BOWLER             5.25
 8        Arshdeep Singh   Retained        BOWLER             4.00
 9         Harpreet Brar    20 Lakh   ALL-ROUNDER             3.80
 10        Vaibhav Arora    20 Lakh        BOWLER             2.00
 11       Raj Angad Bawa    20 Lakh   ALL-ROUNDER             2.00
 12         Nathan Ellis    75 Lakh        BOWLER             0.75
 13    Prabhsimran Singh    20 Lakh  WICKETKEEPER             0.60
 14         Rishi Dhawan    50 Lakh   ALL-ROUNDER             0.55
 15       Sandeep Sharma    50 Lakh        BOWLER             0.50
 16    Bhanuka Rajapaksa    50 Lakh        BATTER             0.50
 17         Benny Howell    40 Lakh   ALL-ROUNDER             0.40
 18          Ishan Porel    20 Lakh        BOWLER             0.25
 19        Prerak Mankad    20 Lakh   ALL-ROUNDER             0.20
 20           Ansh Patel    20 Lakh   ALL-ROUNDER             0.20
 21        Jitesh Sharma    20 Lakh  WICKETKEEPER             0.20
 22  Writtick Chatterjee    20 Lakh   ALL-ROUNDER             0.20
 23        Atharva Taide    20 Lakh   ALL-ROUNDER             0.20
 24        Baltej Dhanda    20 Lakh        BOWLER             0.20

     Cost IN $ (000) 2021 Squad
 0            1560.0       PBKS
 1            1495.0         RR
 2            1202.5         DC
 3            1170.0       PBKS
 4            1072.5         DC
 5             877.5        SRH
 6             780.0        NaN
 7             682.5         MI
 8             520.0       PBKS
 9             494.0       PBKS
 10            260.0        KKR
 11            260.0        NaN
 12             97.5       PBKS
 13             78.0       PBKS
 14             71.5        NaN
 15             65.0        SRH
 16             65.0        NaN
 17             52.0        NaN
 18             32.5       PBKS
 19             26.0        NaN
 20             26.0        NaN
 21             26.0        NaN
 22             26.0        NaN
 23             26.0        NaN
 24             26.0        NaN  ,
          2022 Squad LSG  Base Price          TYPE  COST IN ₹ (CR.)  \
 0              KL Rahul  Draft Pick  WICKETKEEPER            17.00
 1            Avesh Khan     20 Lakh        BOWLER            10.00
 2        Marcus Stoinis  Draft Pick   ALL-ROUNDER             9.20
 3          Jason Holder      1.5 Cr   ALL-ROUNDER             8.75
 4         Krunal Pandya        2 Cr   ALL-ROUNDER             8.25
 5             Mark Wood        2 Cr        BOWLER             7.50
 6       Quinton De Kock        2 Cr  WICKETKEEPER             6.75
 7          Deepak Hooda     75 Lakh   ALL-ROUNDER             5.75
 8         Manish Pandey        1 Cr        BATTER             4.60
 9          Ravi Bishnoi  Draft Pick        BOWLER             4.00
 10   Dushmanta Chameera     50 Lakh        BOWLER             2.00
 11           Evin Lewis        2 Cr        BATTER             2.00
 12           K. Gowtham     50 Lakh   ALL-ROUNDER             0.90
 13          Kyle Mayers     50 Lakh   ALL-ROUNDER             0.50
 14       Shahbaz Nadeem     50 Lakh        BOWLER             0.50
 15  Ankit Singh Rajpoot     20 Lakh        BOWLER             0.50
 16          Manan Vohra     20 Lakh        BATTER             0.20
 17     B. Sai Sudharsan     20 Lakh   ALL-ROUNDER             0.20
 18         Karan Sharma     20 Lakh   ALL-ROUNDER             0.20
 19         Ayush Badoni     20 Lakh   ALL-ROUNDER             0.20
 20          Mohsin Khan     20 Lakh        BOWLER             0.20
 21         Mayank Yadav     20 Lakh        BOWLER             0.20

     Cost IN $ (000) 2021 Squad
 0            2210.0       PBKS
 1            1300.0         DC
 2            1196.0         DC
 3            1137.5        SRH
 4            1072.5         MI
 5             975.0        NaN
 6             877.5         MI
 7             747.5       PBKS
 8             598.0        SRH
 9             520.0       PBKS
 10            260.0        NaN
 11            260.0         RR
 12            117.0        CSK
 13             65.0        NaN
 14             65.0        SRH
 15             65.0        NaN
 16             26.0         RR
 17             26.0        NaN
 18             26.0        NaN
 19             26.0        NaN
 20             26.0         MI
 21             26.0        NaN  ,
         2022 Squad MI Base Price          TYPE  COST IN ₹ (CR.)  \
 0        Rohit Sharma   Retained        BATTER            16.00
 1        Ishan Kishan       2 Cr  WICKETKEEPER            15.25
 2      Jasprit Bumrah   Retained        BOWLER            12.00
 3           Tim David    40 Lakh   ALL-ROUNDER             8.25
 4        Jofra Archer       2 Cr   ALL-ROUNDER             8.00
 5    Suryakumar Yadav   Retained        BATTER             8.00
 6      Kieron Pollard   Retained   ALL-ROUNDER             6.00
 7       Dewald Brevis    20 Lakh        BATTER             3.00
 8         Daniel Sams       1 Cr   ALL-ROUNDER             2.60
 9      N. Tilak Varma    20 Lakh   ALL-ROUNDER             1.70
 10     Murugan Ashwin    20 Lakh        BOWLER             1.60
 11        Tymal Mills       1 Cr        BOWLER             1.50
 12     Jaydev Unadkat    75 Lakh        BOWLER             1.30
 13     Riley Meredith       1 Cr        BOWLER             1.00
 14       Fabian Allen    75 Lakh   ALL-ROUNDER             0.75
 15    Mayank Markande    50 Lakh        BOWLER             0.65
 16       Sanjay Yadav    20 Lakh   ALL-ROUNDER             0.50
 17    Arjun Tendulkar    20 Lakh   ALL-ROUNDER             0.30
 18       Basil Thampi    30 Lakh        BOWLER             0.30
 19   Anmolpreet Singh    20 Lakh        BATTER             0.20
 20        Aryan Juyal    20 Lakh  WICKETKEEPER             0.20
 21    Ramandeep Singh    20 Lakh   ALL-ROUNDER             0.20
 22       Rahul Buddhi    20 Lakh        BATTER             0.20
 23    Hrithik Shokeen    20 Lakh   ALL-ROUNDER             0.20
 24  Mohd. Arshad Khan    20 Lakh   ALL-ROUNDER             0.20

     Cost IN $ (000) 2021 Squad
 0            2080.0         MI
 1            1982.5         MI
 2            1560.0         MI
 3            1072.5        RCB
 4            1040.0         RR
 5            1040.0         MI
 6             780.0         MI
 7             390.0        NaN
 8             338.0        RCB
 9             221.0        NaN
 10            208.0       PBKS
 11            195.0        NaN
 12            169.0         RR
 13            130.0       PBKS
 14             97.5        NaN
 15             84.5         RR
 16             65.0        NaN
 17             39.0         MI
 18             39.0        SRH
 19             26.0         MI
 20             26.0        NaN
 21             26.0        NaN
 22             26.0        NaN
 23             26.0        NaN
 24             26.0        NaN  ,
          2022 Squad RCB Base Price          TYPE  COST IN ₹ (CR.)  \
 0           Virat Kohli   Retained        BATTER            15.00
 1         Glenn Maxwell   Retained   ALL-ROUNDER            11.00
 2     Wanindu Hasaranga       1 Cr   ALL-ROUNDER            10.75
 3         Harshal Patel       2 Cr   ALL-ROUNDER            10.75
 4        Josh Hazlewood       2 Cr        BOWLER             7.75
 5        Faf Du Plessis       2 Cr        BATTER             7.00
 6        Mohammed Siraj   Retained        BOWLER             7.00
 7        Dinesh Karthik       2 Cr  WICKETKEEPER             5.50
 8            Anuj Rawat    20 Lakh  WICKETKEEPER             3.40
 9        Shahbaz Ahamad    30 Lakh   ALL-ROUNDER             2.40
 10         David Willey       2 Cr   ALL-ROUNDER             2.00
 11  Sherfane Rutherford       1 Cr   ALL-ROUNDER             1.00
 12       Mahipal Lomror    40 Lakh   ALL-ROUNDER             0.95
 13           Finn Allen    50 Lakh        BATTER             0.80
 14       Siddharth Kaul    75 Lakh        BOWLER             0.75
 15    Jason Behrendorff    75 Lakh        BOWLER             0.75
 16          Karn Sharma    50 Lakh        BOWLER             0.50
 17  Suyash Prabhudessai    20 Lakh   ALL-ROUNDER             0.30
 18         Chama Milind    20 Lakh        BOWLER             0.25
 19           Akash Deep    20 Lakh        BOWLER             0.20

# Creating Gujarat Titans Dataframe

In [5]:
initial[1]

,2022 Squad GT,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad
0,Rashid Khan,Draft Pick,BOWLER,15.00,1950.0,SRH
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.00,1950.0,MI
2,Lockie Ferguson,2 Cr,BOWLER,10.00,1300.0,KKR
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.00,1170.0,RR
4,Shubman Gill,Draft Pick,BATTER,8.00,1040.0,KKR
5,Mohammad Shami,2 Cr,BOWLER,6.25,812.5,PBKS
6,Yash Dayal,20 Lakh,BOWLER,3.20,416.0,NaN
7,David Miller,1 Cr,BATTER,3.00,390.0,RR
8,R. Sai Kishore,20 Lakh,BOWLER,3.00,390.0,CSK
9,Abhinav Sadarangani,20 Lakh,BATTER,2.60,338.0,NaN
10,Matthew Wade,2 Cr,WICKETKEEPER,2.40,312.0,NaN
11,Alzarri Joseph,75 Lakh,BOWLER,2.40,312.0,NaN
12,Jason Roy,2 Cr,BATTER,2.00,260.0,SRH
13,Wriddhiman Saha,1 Cr,WICKETKEEPER,1.90,247.0,SRH
14,Jayant Yadav,1 Cr,ALL-ROUNDER,1.70,221.0,MI
15,Vijay Shankar,50 Lakh,ALL-ROUNDER,1.40,182.0,SRH
16,Dominic Drakes,75 Lakh,ALL-ROUNDER,1.10,143.0,CSK
17,Varun Aaron,50 Lakh,BOWLER,0.50,65.0,NaN
18,Gurkeerat Singh,50 Lakh,ALL-ROUNDER,0.50,65.0,KKR
19,Noor Ahmad,30 Lakh,BOWLER,0.30,39.0,NaN
20,Darshan Nalkande,20 Lakh,ALL-ROUNDER,0.20,26.0,PBKS
21,Pradeep Sangwan,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN

In [6]:
gujarat_titans=initial[1]

In [7]:
gujarat_titans["Team"]="Gujarat Titans"

In [8]:
gujarat_titans.rename(columns={"2022 Squad GT":"Player"},inplace=True)

In [9]:
gujarat_titans

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.00,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.00,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.00,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.00,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.00,1040.0,KKR,Gujarat Titans
5,Mohammad Shami,2 Cr,BOWLER,6.25,812.5,PBKS,Gujarat Titans
6,Yash Dayal,20 Lakh,BOWLER,3.20,416.0,NaN,Gujarat Titans
7,David Miller,1 Cr,BATTER,3.00,390.0,RR,Gujarat Titans
8,R. Sai Kishore,20 Lakh,BOWLER,3.00,390.0,CSK,Gujarat Titans
9,Abhinav Sadarangani,20 Lakh,BATTER,2.60,338.0,NaN,Gujarat Titans
10,Matthew Wade,2 Cr,WICKETKEEPER,2.40,312.0,NaN,Gujarat Titans
11,Alzarri Joseph,75 Lakh,BOWLER,2.40,312.0,NaN,Gujarat Titans
12,Jason Roy,2 Cr,BATTER,2.00,260.0,SRH,Gujarat Titans
13,Wriddhiman Saha,1 Cr,WICKETKEEPER,1.90,247.0,SRH,Gujarat Titans
14,Jayant Yadav,1 Cr,ALL-ROUNDER,1.70,221.0,MI,Gujarat Titans
15,Vijay Shankar,50 Lakh,ALL-ROUNDER,1.40,182.0,SRH,Gujarat Titans
16,Dominic Drakes,75 Lakh,ALL-ROUNDER,1.10,143.0,CSK,Gujarat Titans
17,Varun Aaron,50 Lakh,BOWLER,0.50,65.0,NaN,Gujarat Titans
18,Gurkeerat Singh,50 Lakh,ALL-ROUNDER,0.50,65.0,KKR,Gujarat Titans
19,Noor Ahmad,30 Lakh,BOWLER,0.30,39.0,NaN,Gujarat Titans
20,Darshan Nalkande,20 Lakh,ALL-ROUNDER,0.20,26.0,PBKS,Gujarat Titans
21,Pradeep Sangwan,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN,Gujarat Titans

# Creating Chennai Super Kings Dataframe

In [10]:
initial[2]

,2022 Squad CSK,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad
0,Ravindra Jadeja,Retained,ALL-ROUNDER,16.00,2080.0,CSK
1,Deepak Chahar,2 Cr,BOWLER,14.00,1820.0,CSK
2,MS Dhoni,Retained,WICKETKEEPER,12.00,1560.0,CSK
3,Moeen Ali,Retained,ALL-ROUNDER,8.00,1040.0,CSK
4,Ambati Rayudu,2 Cr,WICKETKEEPER,6.75,877.5,CSK
5,Ruturaj Gaikwad,Retained,BATTER,6.00,780.0,CSK
6,Dwayne Bravo,2 Cr,ALL-ROUNDER,4.40,572.0,CSK
7,Shivam Dube,50 Lakh,ALL-ROUNDER,4.00,520.0,RR
8,Chris Jordan,2 Cr,ALL-ROUNDER,3.60,468.0,PBKS
9,Robin Uthappa,2 Cr,BATTER,2.00,260.0,CSK
10,Mitchell Santner,1 Cr,ALL-ROUNDER,1.90,247.0,CSK
11,Adam Milne,1.5 Cr,BOWLER,1.90,247.0,MI
12,Rajvardhan Hangargekar,30 Lakh,ALL-ROUNDER,1.50,195.0,NaN
13,Prashant Solanki,20 Lakh,BOWLER,1.20,156.0,NaN
14,Devon Conway,1 Cr,BATTER,1.00,130.0,NaN
15,Maheesh Theekshana,50 Lakh,BOWLER,0.70,91.0,NaN
16,Dwaine Pretorius,50 Lakh,ALL-ROUNDER,0.50,65.0,NaN
17,K.Bhagath Varma,20 Lakh,ALL-ROUNDER,0.20,26.0,CSK
18,Simarjeet Singh,20 Lakh,BOWLER,0.20,26.0,MI
19,N. Jagadeesan,20 Lakh,WICKETKEEPER,0.20,26.0,CSK
20,C.Hari Nishaanth,20 Lakh,BATTER,0.20,26.0,CSK
21,K.M. Asif,20 Lakh,BOWLER,0.20,26.0,CSK
22,Tushar Deshpande,20 Lakh,BOWLER,0.20,26.0,NaN
23,Subhranshu Senapati,20 Lakh,BATTER,0.20,26.0,NaN
24,Mukesh Choudhary,20 Lakh,BOWLER,0.20,26.0,NaN

In [11]:
csk=initial[2]
csk["Team"]="Chennai Super Kings"
csk.rename(columns={"2022 Squad CSK":"Player"},inplace=True)
#Appending into 1 Dataframe
final=gujarat_titans.append(csk,ignore_index=True)
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.00,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.00,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.00,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.00,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.00,1040.0,KKR,Gujarat Titans
5,Mohammad Shami,2 Cr,BOWLER,6.25,812.5,PBKS,Gujarat Titans
6,Yash Dayal,20 Lakh,BOWLER,3.20,416.0,NaN,Gujarat Titans
7,David Miller,1 Cr,BATTER,3.00,390.0,RR,Gujarat Titans
8,R. Sai Kishore,20 Lakh,BOWLER,3.00,390.0,CSK,Gujarat Titans
9,Abhinav Sadarangani,20 Lakh,BATTER,2.60,338.0,NaN,Gujarat Titans
10,Matthew Wade,2 Cr,WICKETKEEPER,2.40,312.0,NaN,Gujarat Titans
11,Alzarri Joseph,75 Lakh,BOWLER,2.40,312.0,NaN,Gujarat Titans
12,Jason Roy,2 Cr,BATTER,2.00,260.0,SRH,Gujarat Titans
13,Wriddhiman Saha,1 Cr,WICKETKEEPER,1.90,247.0,SRH,Gujarat Titans
14,Jayant Yadav,1 Cr,ALL-ROUNDER,1.70,221.0,MI,Gujarat Titans
15,Vijay Shankar,50 Lakh,ALL-ROUNDER,1.40,182.0,SRH,Gujarat Titans
16,Dominic Drakes,75 Lakh,ALL-ROUNDER,1.10,143.0,CSK,Gujarat Titans
17,Varun Aaron,50 Lakh,BOWLER,0.50,65.0,NaN,Gujarat Titans
18,Gurkeerat Singh,50 Lakh,ALL-ROUNDER,0.50,65.0,KKR,Gujarat Titans
19,Noor Ahmad,30 Lakh,BOWLER,0.30,39.0,NaN,Gujarat Titans
20,Darshan Nalkande,20 Lakh,ALL-ROUNDER,0.20,26.0,PBKS,Gujarat Titans
21,Pradeep Sangwan,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN,Gujarat Titans
22,Ravindra Jadeja,Retained,ALL-ROUNDER,16.00,2080.0,CSK,Chennai Super Kings
23,Deepak Chahar,2 Cr,BOWLER,14.00,1820.0,CSK,Chennai Super Kings
24,MS Dhoni,Retained,WICKETKEEPER,12.00,1560.0,CSK,Chennai Super Kings
25,Moeen Ali,Retained,ALL-ROUNDER,8.00,1040.0,CSK,Chennai Super Kings
26,Ambati Rayudu,2 Cr,WICKETKEEPER,6.75,877.5,CSK,Chennai Super Kings
27,Ruturaj Gaikwad,Retained,BATTER,6.00,780.0,CSK,Chennai Super Kings
28,Dwayne Bravo,2 Cr,ALL-ROUNDER,4.40,572.0,CSK,Chennai Super Kings
29,Shivam Dube,50 Lakh,ALL-ROUNDER,4.00,520.0,RR,Chennai Super Kings
30,Chris Jordan,2 Cr,ALL-ROUNDER,3.60,468.0,PBKS,Chennai Super Kings
31,Robin Uthappa,2 Cr,BATTER,2.00,260.0,CSK,Chennai Super Kings
32,Mitchell Santner,1 Cr,ALL-ROUNDER,1.90,247.0,CSK,Chennai Super Kings
33,Adam Milne,1.5 Cr,BOWLER,1.90,247.0,MI,Chennai Super Kings
34,Rajvardhan Hangargekar,30 Lakh,ALL-ROUNDER,1.50,195.0,NaN,Chennai Super Kings
35,Prashant Solanki,20 Lakh,BOWLER,1.20,156.0,NaN,Chennai Super Kings
36,Devon Conway,1 Cr,BATTER,1.00,130.0,NaN,Chennai Super Kings
37,Maheesh Theekshana,50 Lakh,BOWLER,0.70,91.0,NaN,Chennai Super Kings
38,Dwaine Pretorius,50 Lakh,ALL-ROUNDER,0.50,65.0,NaN,Chennai Super Kings
39,K.Bhagath Varma,20 Lakh,ALL-ROUNDER,0.20,26.0,CSK,Chennai Super Kings
40,Simarjeet Singh,20 Lakh,BOWLER,0.20,26.0,MI,Chennai Super Kings
41,N. Jagadeesan,20 Lakh,WICKETKEEPER,0.20,26.0,CSK,Chennai Super Kings
42,C.Hari Nishaanth,20 Lakh,BATTER,0.20,26.0,CSK,Chennai Super Kings
43,K.M. Asif,20 Lakh,BOWLER,0.20,26.0,CSK,Chennai Super Kings
44,Tushar Deshpande,20 Lakh,BOWLER,0.20,26.0,NaN,Chennai Super Kings
45,Subhranshu Senapati,20 Lakh,BATTER,0.20,26.0,NaN,Chennai Super Kings
46,Mukesh Choudhary,20 Lakh,BOWLER,0.20,26.0,NaN,Chennai Super Kings

# Creating Delhi Capitals Dataframe

In [12]:
initial[3]

,2022 Squad DC,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad
0,Rishabh Pant,Retained,WICKETKEEPER,16.00,2080.0,DC
1,Shardul Thakur,2 Cr,BOWLER,10.75,1397.5,CSK
2,Axar Patel,Retained,ALL-ROUNDER,9.00,1170.0,DC
3,Prithvi Shaw,Retained,BATTER,7.50,975.0,DC
4,Mitchell Marsh,2 Cr,ALL-ROUNDER,6.50,845.0,NaN
5,Anrich Nortje,Retained,BOWLER,6.50,845.0,DC
6,David Warner,2 Cr,BATTER,6.25,812.5,SRH
7,Syed Khaleel Ahmed,50 Lakh,BOWLER,5.25,682.5,SRH
8,Chetan Sakariya,50 Lakh,BOWLER,4.20,546.0,RR
9,Rovman Powell,75 Lakh,BATTER,2.80,364.0,NaN
10,K.S. Bharat,20 Lakh,WICKETKEEPER,2.00,260.0,RCB
11,Mustafizur Rahman,2 Cr,BOWLER,2.00,260.0,RR
12,Kuldeep Yadav,1 Cr,BOWLER,2.00,260.0,KKR
13,Kamlesh Nagarkoti,40 Lakh,ALL-ROUNDER,1.10,143.0,KKR
14,Mandeep Singh,50 Lakh,BATTER,1.10,143.0,PBKS
15,Lalit Yadav,20 Lakh,ALL-ROUNDER,0.65,84.5,DC
16,Tim Seifert,50 Lakh,WICKETKEEPER,0.50,65.0,KKR
17,Pravin Dubey,20 Lakh,ALL-ROUNDER,0.50,65.0,DC
18,Lungisani Ngidi,50 Lakh,BOWLER,0.50,65.0,CSK
19,Yash Dhull,20 Lakh,ALL-ROUNDER,0.50,65.0,NaN
20,Ashwin Hebbar,20 Lakh,BATTER,0.20,26.0,NaN
21,Sarfaraz Khan,20 Lakh,ALL-ROUNDER,0.20,26.0,PBKS
22,Ripal Patel,20 Lakh,ALL-ROUNDER,0.20,26.0,DC
23,Vicky Ostwal,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN

In [13]:
dc=initial[3]
dc["Team"]="Delhi Capitals"
dc.rename(columns={"2022 Squad DC":"Player"},inplace=True)
#Appending into 1 Dataframe
final=final.append(dc,ignore_index=True)
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
66,Yash Dhull,20 Lakh,ALL-ROUNDER,0.5,65.0,NaN,Delhi Capitals
67,Ashwin Hebbar,20 Lakh,BATTER,0.2,26.0,NaN,Delhi Capitals
68,Sarfaraz Khan,20 Lakh,ALL-ROUNDER,0.2,26.0,PBKS,Delhi Capitals
69,Ripal Patel,20 Lakh,ALL-ROUNDER,0.2,26.0,DC,Delhi Capitals
70,Vicky Ostwal,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Delhi Capitals

# Creating Kolkata Knight Riders Dataframe

In [14]:
initial[4]

,2022 Squad KKR,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad
0,Shreyas Iyer,2 Cr,BATTER,12.25,1592.5,DC
1,Andre Russell,Retained,ALL-ROUNDER,12.00,1560.0,KKR
2,Nitish Rana,1 Cr,ALL-ROUNDER,8.00,1040.0,KKR
3,Venkatesh Iyer,Retained,ALL-ROUNDER,8.00,1040.0,KKR
4,Varun Chakaravarthy,Retained,BOWLER,8.00,1040.0,KKR
5,Pat Cummins,2 Cr,ALL-ROUNDER,7.25,942.5,KKR
6,Shivam Mavi,40 Lakh,ALL-ROUNDER,7.25,942.5,KKR
7,Sunil Narine,Retained,ALL-ROUNDER,6.00,780.0,KKR
8,Sam Billings,2 Cr,WICKETKEEPER,2.00,260.0,DC
9,Umesh Yadav,2 Cr,BOWLER,2.00,260.0,DC
10,Tim Southee,1.5 Cr,BOWLER,1.50,195.0,KKR
11,Alex Hales,1.5 Cr,BATTER,1.50,195.0,NaN
12,Ajinkya Rahane,1 Cr,BATTER,1.00,130.0,DC
13,Mohammad Nabi,1 Cr,ALL-ROUNDER,1.00,130.0,SRH
14,Sheldon Jackson,30 Lakh,WICKETKEEPER,0.60,78.0,KKR
15,Rinku Singh,20 Lakh,BATTER,0.55,71.5,NaN
16,Ashok Sharma,20 Lakh,BOWLER,0.55,71.5,NaN
17,Chamika Karunaratne,50 Lakh,ALL-ROUNDER,0.50,65.0,NaN
18,Abhijeet Tomar,20 Lakh,BATTER,0.40,52.0,NaN
19,Rasikh Dar,20 Lakh,BOWLER,0.20,26.0,NaN
20,Anukul Roy,20 Lakh,ALL-ROUNDER,0.20,26.0,MI
21,Baba Indrajith,20 Lakh,WICKETKEEPER,0.20,26.0,NaN
22,Aman Khan,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
23,Ramesh Kumar,20 Lakh,BATTER,0.20,26.0,NaN
24,Pratham Singh,20 Lakh,BATTER,0.20,26.0,NaN

In [15]:
kkr=initial[4]
kkr["Team"]="Kolkata Knight Riders"
kkr.rename(columns={"2022 Squad KKR":"Player"},inplace=True)
#Appending into 1 Dataframe
final=final.append(kkr,ignore_index=True)
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
91,Anukul Roy,20 Lakh,ALL-ROUNDER,0.2,26.0,MI,Kolkata Knight Riders
92,Baba Indrajith,20 Lakh,WICKETKEEPER,0.2,26.0,NaN,Kolkata Knight Riders
93,Aman Khan,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Kolkata Knight Riders
94,Ramesh Kumar,20 Lakh,BATTER,0.2,26.0,NaN,Kolkata Knight Riders
95,Pratham Singh,20 Lakh,BATTER,0.2,26.0,NaN,Kolkata Knight Riders

# Creating Punjab Kings Dataframe

In [16]:
initial[5]

,2022 Squad PBKS,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad
0,Mayank Agarwal,Retained,BATTER,12.00,1560.0,PBKS
1,Liam Livingstone,1 Cr,ALL-ROUNDER,11.50,1495.0,RR
2,Kagiso Rabada,2 Cr,BOWLER,9.25,1202.5,DC
3,Shahrukh Khan,40 Lakh,ALL-ROUNDER,9.00,1170.0,PBKS
4,Shikhar Dhawan,2 Cr,BATTER,8.25,1072.5,DC
5,Jonny Bairstow,1.5 Cr,WICKETKEEPER,6.75,877.5,SRH
6,Odean Smith,1 Cr,ALL-ROUNDER,6.00,780.0,NaN
7,Rahul Chahar,75 Lakh,BOWLER,5.25,682.5,MI
8,Arshdeep Singh,Retained,BOWLER,4.00,520.0,PBKS
9,Harpreet Brar,20 Lakh,ALL-ROUNDER,3.80,494.0,PBKS
10,Vaibhav Arora,20 Lakh,BOWLER,2.00,260.0,KKR
11,Raj Angad Bawa,20 Lakh,ALL-ROUNDER,2.00,260.0,NaN
12,Nathan Ellis,75 Lakh,BOWLER,0.75,97.5,PBKS
13,Prabhsimran Singh,20 Lakh,WICKETKEEPER,0.60,78.0,PBKS
14,Rishi Dhawan,50 Lakh,ALL-ROUNDER,0.55,71.5,NaN
15,Sandeep Sharma,50 Lakh,BOWLER,0.50,65.0,SRH
16,Bhanuka Rajapaksa,50 Lakh,BATTER,0.50,65.0,NaN
17,Benny Howell,40 Lakh,ALL-ROUNDER,0.40,52.0,NaN
18,Ishan Porel,20 Lakh,BOWLER,0.25,32.5,PBKS
19,Prerak Mankad,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
20,Ansh Patel,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
21,Jitesh Sharma,20 Lakh,WICKETKEEPER,0.20,26.0,NaN
22,Writtick Chatterjee,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
23,Atharva Taide,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
24,Baltej Dhanda,20 Lakh,BOWLER,0.20,26.0,NaN

In [17]:
pbks=initial[5]
pbks["Team"]="Punjab Kings"
pbks.rename(columns={"2022 Squad PBKS":"Player"},inplace=True)
#Appending into 1 Dataframe
final=final.append(pbks,ignore_index=True)
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
116,Ansh Patel,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Punjab Kings
117,Jitesh Sharma,20 Lakh,WICKETKEEPER,0.2,26.0,NaN,Punjab Kings
118,Writtick Chatterjee,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Punjab Kings
119,Atharva Taide,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Punjab Kings
120,Baltej Dhanda,20 Lakh,BOWLER,0.2,26.0,NaN,Punjab Kings

# Creating Lucknow Super Giants Dataframe

In [18]:
initial[6]

,2022 Squad LSG,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad
0,KL Rahul,Draft Pick,WICKETKEEPER,17.00,2210.0,PBKS
1,Avesh Khan,20 Lakh,BOWLER,10.00,1300.0,DC
2,Marcus Stoinis,Draft Pick,ALL-ROUNDER,9.20,1196.0,DC
3,Jason Holder,1.5 Cr,ALL-ROUNDER,8.75,1137.5,SRH
4,Krunal Pandya,2 Cr,ALL-ROUNDER,8.25,1072.5,MI
5,Mark Wood,2 Cr,BOWLER,7.50,975.0,NaN
6,Quinton De Kock,2 Cr,WICKETKEEPER,6.75,877.5,MI
7,Deepak Hooda,75 Lakh,ALL-ROUNDER,5.75,747.5,PBKS
8,Manish Pandey,1 Cr,BATTER,4.60,598.0,SRH
9,Ravi Bishnoi,Draft Pick,BOWLER,4.00,520.0,PBKS
10,Dushmanta Chameera,50 Lakh,BOWLER,2.00,260.0,NaN
11,Evin Lewis,2 Cr,BATTER,2.00,260.0,RR
12,K. Gowtham,50 Lakh,ALL-ROUNDER,0.90,117.0,CSK
13,Kyle Mayers,50 Lakh,ALL-ROUNDER,0.50,65.0,NaN
14,Shahbaz Nadeem,50 Lakh,BOWLER,0.50,65.0,SRH
15,Ankit Singh Rajpoot,20 Lakh,BOWLER,0.50,65.0,NaN
16,Manan Vohra,20 Lakh,BATTER,0.20,26.0,RR
17,B. Sai Sudharsan,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
18,Karan Sharma,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
19,Ayush Badoni,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
20,Mohsin Khan,20 Lakh,BOWLER,0.20,26.0,MI
21,Mayank Yadav,20 Lakh,BOWLER,0.20,26.0,NaN

In [19]:
lsg=initial[6]
lsg["Team"]="Lucknow Super Giants"
lsg.rename(columns={"2022 Squad LSG":"Player"},inplace=True)
#Appending into 1 Dataframe
final=final.append(lsg,ignore_index=True)
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
138,B. Sai Sudharsan,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Lucknow Super Giants
139,Karan Sharma,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Lucknow Super Giants
140,Ayush Badoni,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Lucknow Super Giants
141,Mohsin Khan,20 Lakh,BOWLER,0.2,26.0,MI,Lucknow Super Giants
142,Mayank Yadav,20 Lakh,BOWLER,0.2,26.0,NaN,Lucknow Super Giants

# Creating Mumbai Indians Dataframe

In [20]:
initial[7]

,2022 Squad MI,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad
0,Rohit Sharma,Retained,BATTER,16.00,2080.0,MI
1,Ishan Kishan,2 Cr,WICKETKEEPER,15.25,1982.5,MI
2,Jasprit Bumrah,Retained,BOWLER,12.00,1560.0,MI
3,Tim David,40 Lakh,ALL-ROUNDER,8.25,1072.5,RCB
4,Jofra Archer,2 Cr,ALL-ROUNDER,8.00,1040.0,RR
5,Suryakumar Yadav,Retained,BATTER,8.00,1040.0,MI
6,Kieron Pollard,Retained,ALL-ROUNDER,6.00,780.0,MI
7,Dewald Brevis,20 Lakh,BATTER,3.00,390.0,NaN
8,Daniel Sams,1 Cr,ALL-ROUNDER,2.60,338.0,RCB
9,N. Tilak Varma,20 Lakh,ALL-ROUNDER,1.70,221.0,NaN
10,Murugan Ashwin,20 Lakh,BOWLER,1.60,208.0,PBKS
11,Tymal Mills,1 Cr,BOWLER,1.50,195.0,NaN
12,Jaydev Unadkat,75 Lakh,BOWLER,1.30,169.0,RR
13,Riley Meredith,1 Cr,BOWLER,1.00,130.0,PBKS
14,Fabian Allen,75 Lakh,ALL-ROUNDER,0.75,97.5,NaN
15,Mayank Markande,50 Lakh,BOWLER,0.65,84.5,RR
16,Sanjay Yadav,20 Lakh,ALL-ROUNDER,0.50,65.0,NaN
17,Arjun Tendulkar,20 Lakh,ALL-ROUNDER,0.30,39.0,MI
18,Basil Thampi,30 Lakh,BOWLER,0.30,39.0,SRH
19,Anmolpreet Singh,20 Lakh,BATTER,0.20,26.0,MI
20,Aryan Juyal,20 Lakh,WICKETKEEPER,0.20,26.0,NaN
21,Ramandeep Singh,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
22,Rahul Buddhi,20 Lakh,BATTER,0.20,26.0,NaN
23,Hrithik Shokeen,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
24,Mohd. Arshad Khan,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN

In [21]:
mi=initial[7]
mi["Team"]="Mumbai Indians"
mi.rename(columns={"2022 Squad MI":"Player"},inplace=True)
#Appending into 1 Dataframe
final=final.append(mi,ignore_index=True)
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
163,Aryan Juyal,20 Lakh,WICKETKEEPER,0.2,26.0,NaN,Mumbai Indians
164,Ramandeep Singh,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Mumbai Indians
165,Rahul Buddhi,20 Lakh,BATTER,0.2,26.0,NaN,Mumbai Indians
166,Hrithik Shokeen,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Mumbai Indians
167,Mohd. Arshad Khan,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Mumbai Indians

# Creating Royal Challengers Bangalore Dataframe

In [22]:
initial[8]

,2022 Squad RCB,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad
0,Virat Kohli,Retained,BATTER,15.00,1950.0,RCB
1,Glenn Maxwell,Retained,ALL-ROUNDER,11.00,1430.0,RCB
2,Wanindu Hasaranga,1 Cr,ALL-ROUNDER,10.75,1397.5,RCB
3,Harshal Patel,2 Cr,ALL-ROUNDER,10.75,1397.5,RCB
4,Josh Hazlewood,2 Cr,BOWLER,7.75,1007.5,CSK
5,Faf Du Plessis,2 Cr,BATTER,7.00,910.0,CSK
6,Mohammed Siraj,Retained,BOWLER,7.00,910.0,RCB
7,Dinesh Karthik,2 Cr,WICKETKEEPER,5.50,715.0,KKR
8,Anuj Rawat,20 Lakh,WICKETKEEPER,3.40,442.0,RR
9,Shahbaz Ahamad,30 Lakh,ALL-ROUNDER,2.40,312.0,RCB
10,David Willey,2 Cr,ALL-ROUNDER,2.00,260.0,NaN
11,Sherfane Rutherford,1 Cr,ALL-ROUNDER,1.00,130.0,NaN
12,Mahipal Lomror,40 Lakh,ALL-ROUNDER,0.95,123.5,RR
13,Finn Allen,50 Lakh,BATTER,0.80,104.0,RCB
14,Siddharth Kaul,75 Lakh,BOWLER,0.75,97.5,SRH
15,Jason Behrendorff,75 Lakh,BOWLER,0.75,97.5,CSK
16,Karn Sharma,50 Lakh,BOWLER,0.50,65.0,CSK
17,Suyash Prabhudessai,20 Lakh,ALL-ROUNDER,0.30,39.0,RCB
18,Chama Milind,20 Lakh,BOWLER,0.25,32.5,NaN
19,Akash Deep,20 Lakh,BOWLER,0.20,26.0,RCB
20,Aneeshwar Gautam,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
21,Luvnith Sisodia,20 Lakh,WICKETKEEPER,0.20,26.0,NaN

In [23]:
rcb=initial[8]
rcb["Team"]="Royal Challengers Bangalore"
rcb.rename(columns={"2022 Squad RCB":"Player"},inplace=True)
#Appending into 1 Dataframe
final=final.append(rcb,ignore_index=True)
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.00,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.00,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.00,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.00,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.00,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
185,Suyash Prabhudessai,20 Lakh,ALL-ROUNDER,0.30,39.0,RCB,Royal Challengers Bangalore
186,Chama Milind,20 Lakh,BOWLER,0.25,32.5,NaN,Royal Challengers Bangalore
187,Akash Deep,20 Lakh,BOWLER,0.20,26.0,RCB,Royal Challengers Bangalore
188,Aneeshwar Gautam,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN,Royal Challengers Bangalore
189,Luvnith Sisodia,20 Lakh,WICKETKEEPER,0.20,26.0,NaN,Royal Challengers Bangalore

# Creating Rajasthan Royals Dataframe

In [24]:
initial[9]

,2022 Squad RR,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad
0,Sanju Samson,Retained,WICKETKEEPER,14.00,1820.0,RR
1,Jos Buttler,Retained,WICKETKEEPER,10.00,1300.0,RR
2,Prasidh Krishna,1 Cr,BOWLER,10.00,1300.0,KKR
3,Shimron Hetmyer,1.5 Cr,BATTER,8.50,1105.0,DC
4,Trent Boult,2 Cr,BOWLER,8.00,1040.0,MI
5,Devdutt Padikkal,2 Cr,BATTER,7.75,1007.5,RCB
6,Yuzvendra Chahal,2 Cr,BOWLER,6.50,845.0,RCB
7,R. Ashwin,2 Cr,ALL-ROUNDER,5.00,650.0,DC
8,Yashaswi Jaiswal,Retained,BATTER,4.00,520.0,RR
9,Riyan Parag,30 Lakh,ALL-ROUNDER,3.80,494.0,RR
10,Navdeep Saini,75 Lakh,BOWLER,2.60,338.0,RCB
11,Nathan Coulter-Nile,2 Cr,BOWLER,2.00,260.0,MI
12,James Neesham,1.5 Cr,ALL-ROUNDER,1.50,195.0,MI
13,Karun Nair,50 Lakh,BATTER,1.40,182.0,KKR
14,Rassie Van Der Dussen,1 Cr,BATTER,1.00,130.0,NaN
15,Obed Mccoy,75 Lakh,BOWLER,0.75,97.5,NaN
16,Daryl Mitchell,75 Lakh,ALL-ROUNDER,0.75,97.5,NaN
17,K.C Cariappa,20 Lakh,BOWLER,0.30,39.0,RR
18,Anunay Singh,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
19,Kuldeep Sen,20 Lakh,BOWLER,0.20,26.0,NaN
20,Dhruv Jurel,20 Lakh,WICKETKEEPER,0.20,26.0,NaN
21,Tejas Baroka,20 Lakh,BOWLER,0.20,26.0,NaN
22,Kuldip Yadav,20 Lakh,BOWLER,0.20,26.0,RR
23,Shubham Garhwal,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN

In [25]:
rr=initial[9]
rr["Team"]="Rajasthan Royals"
rr.rename(columns={"2022 Squad RR":"Player"},inplace=True)
#Appending into 1 Dataframe
final=final.append(rr,ignore_index=True)
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
209,Kuldeep Sen,20 Lakh,BOWLER,0.2,26.0,NaN,Rajasthan Royals
210,Dhruv Jurel,20 Lakh,WICKETKEEPER,0.2,26.0,NaN,Rajasthan Royals
211,Tejas Baroka,20 Lakh,BOWLER,0.2,26.0,NaN,Rajasthan Royals
212,Kuldip Yadav,20 Lakh,BOWLER,0.2,26.0,RR,Rajasthan Royals
213,Shubham Garhwal,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Rajasthan Royals

# Creating Sunrisers Hyderabad Dataframe

In [26]:
initial[10]

,2022 Squad SRH,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad
0,Kane Williamson,Retained,BATTER,14.00,1820.0,SRH
1,Nicholas Pooran,1.5 Cr,WICKETKEEPER,10.75,1397.5,PBKS
2,Washington Sundar,1.5 Cr,ALL-ROUNDER,8.75,1137.5,RCB
3,Rahul Tripathi,40 Lakh,BATTER,8.50,1105.0,KKR
4,Romario Shepherd,75 Lakh,ALL-ROUNDER,7.75,1007.5,NaN
5,Abhishek Sharma,20 Lakh,ALL-ROUNDER,6.50,845.0,SRH
6,Marco Jansen,50 Lakh,ALL-ROUNDER,4.20,546.0,MI
7,Bhuvneshwar Kumar,2 Cr,BOWLER,4.20,546.0,SRH
8,T. Natarajan,1 Cr,BOWLER,4.00,520.0,SRH
9,Abdul Samad,Retained,ALL-ROUNDER,4.00,520.0,SRH
10,Umran Malik,Retained,BOWLER,4.00,520.0,SRH
11,Kartik Tyagi,20 Lakh,BOWLER,4.00,520.0,RR
12,Aiden Markram,1 Cr,BATTER,2.60,338.0,PBKS
13,Sean Abbott,75 Lakh,BOWLER,2.40,312.0,NaN
14,Glenn Phillips,1.5 Cr,WICKETKEEPER,1.50,195.0,RR
15,Shreyas Gopal,20 Lakh,BOWLER,0.75,97.5,RR
16,Vishnu Vinod,20 Lakh,WICKETKEEPER,0.50,65.0,DC
17,Fazalhaq Farooqi,50 Lakh,BOWLER,0.50,65.0,NaN
18,Priyam Garg,20 Lakh,BATTER,0.20,26.0,SRH
19,R Samarth,20 Lakh,BATTER,0.20,26.0,NaN
20,Jagadeesha Suchith,20 Lakh,BOWLER,0.20,26.0,SRH
21,Shashank Singh,20 Lakh,ALL-ROUNDER,0.20,26.0,NaN
22,Saurabh Dubey,20 Lakh,BOWLER,0.20,26.0,NaN

In [27]:
srh=initial[10]
srh["Team"]="Sunrisers Hyderabad"
srh.rename(columns={"2022 Squad SRH":"Player"},inplace=True)
#Appending into 1 Dataframe
final=final.append(srh,ignore_index=True)
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
232,Priyam Garg,20 Lakh,BATTER,0.2,26.0,SRH,Sunrisers Hyderabad
233,R Samarth,20 Lakh,BATTER,0.2,26.0,NaN,Sunrisers Hyderabad
234,Jagadeesha Suchith,20 Lakh,BOWLER,0.2,26.0,SRH,Sunrisers Hyderabad
235,Shashank Singh,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Sunrisers Hyderabad
236,Saurabh Dubey,20 Lakh,BOWLER,0.2,26.0,NaN,Sunrisers Hyderabad

# Adding Information of Unsold Players

In [28]:
initial[11]

,Players,TYPE,Base Price IN ₹ (CR.),Base Price IN $ (000),2021 Squad
0,Suresh Raina,BATTER,2 Cr,NaN,CSK
1,Steve Smith,BATTER,2 Cr,NaN,DC
2,Shakib Al Hasan,ALL-ROUNDER,2 Cr,NaN,KKR
3,Amit Mishra,BOWLER,1.5 Cr,NaN,DC
4,Adil Rashid,BOWLER,2 Cr,NaN,PBKS
...,...,...,...,...,...
391,Sairaj Patil,BATTER,20 Lakh,NaN,NaN
392,Monu Singh,BOWLER,20 Lakh,NaN,NaN
393,Nivethan Radhakrishnan,BOWLER,20 Lakh,NaN,NaN
394,Lance Morris,BOWLER,20 Lakh,NaN,NaN
395,Aaron Hardie,ALL-ROUNDER,20 Lakh,NaN,NaN

In [29]:
test=initial[11]

# Making Changes to append 
We need to make some changes to this dataframe in order to append to the final dataframe

In [30]:
#rename as same as final dataframe
test.rename(columns={"Base Price IN ₹ (CR.)":"Base Price"},inplace=True)

In [31]:
#rename as same as final dataframe
test.rename(columns={"Players":"Player"},inplace=True)

In [32]:
#dropping unwanted column
test.drop("Base Price IN $ (000)",axis=1,inplace=True)

In [33]:
#creating new columns with null values as same as final dataframe
test["COST IN ₹ (CR.)"]= np.nan

In [34]:
#creating new columns with null values as same as final dataframe
test["Cost IN $ (000)"]= np.nan

In [35]:
#Adding Team name as Unsold
test["Team"]="Unsold"

In [36]:
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
232,Priyam Garg,20 Lakh,BATTER,0.2,26.0,SRH,Sunrisers Hyderabad
233,R Samarth,20 Lakh,BATTER,0.2,26.0,NaN,Sunrisers Hyderabad
234,Jagadeesha Suchith,20 Lakh,BOWLER,0.2,26.0,SRH,Sunrisers Hyderabad
235,Shashank Singh,20 Lakh,ALL-ROUNDER,0.2,26.0,NaN,Sunrisers Hyderabad
236,Saurabh Dubey,20 Lakh,BOWLER,0.2,26.0,NaN,Sunrisers Hyderabad

In [37]:
final.columns

Index(['Player', 'Base Price', 'TYPE', 'COST IN ₹ (CR.)', 'Cost IN $ (000)',
       '2021 Squad', 'Team'],
      dtype='object')

In [38]:
#reordering the columns as same as final dataframe
test=test[['Player','Base Price', 'TYPE', 'COST IN ₹ (CR.)', 'Cost IN $ (000)','2021 Squad', 'Team']]

In [39]:
final=final.append(test,ignore_index=True)

In [40]:
final

,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2021 Squad,Team
0,Rashid Khan,Draft Pick,BOWLER,15.0,1950.0,SRH,Gujarat Titans
1,Hardik Pandya,Draft Pick,ALL-ROUNDER,15.0,1950.0,MI,Gujarat Titans
2,Lockie Ferguson,2 Cr,BOWLER,10.0,1300.0,KKR,Gujarat Titans
3,Rahul Tewatia,40 Lakh,ALL-ROUNDER,9.0,1170.0,RR,Gujarat Titans
4,Shubman Gill,Draft Pick,BATTER,8.0,1040.0,KKR,Gujarat Titans
...,...,...,...,...,...,...,...
628,Sairaj Patil,20 Lakh,BATTER,NaN,NaN,NaN,Unsold
629,Monu Singh,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
630,Nivethan Radhakrishnan,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
631,Lance Morris,20 Lakh,BOWLER,NaN,NaN,NaN,Unsold
632,Aaron Hardie,20 Lakh,ALL-ROUNDER,NaN,NaN,NaN,Unsold

# Exporting the final Dataframe as CSV file

In [41]:
final.to_csv("ipl_2022_dataset.csv")